### ISSUE TITLE
UE 5.3 Oculus - Error in the maps

### ISSUE THREAD

**Issue by alefriant** [oculus-samples/Unreal-GraphicsShowcase#2]
Hi @AlexThiv 
I found this problem when trying to open the file. Will be great if you can fix it,
I'm using the custom Unreal-Oculus 5.3.0
Thanks!
Alejandro

![image](https://github.com/oculus-samples/Unreal-GraphicsShowcase/assets/84304509/f657edf9-b57c-487f-8cf1-2bebd6b37325)

**Comment by AlexThiv** [comment]
Hi @alefriant,

This might be related to lfs. Did you download the code directly or did you clone it?

You will need to install lfs and then git clone the repo.

We will update the readme to specify this, thanks for raising the issue.

**Comment by AlexThiv** [comment]
We updated the readme with information about cloning. Feel free to reopen if you still encounter the issue.

**Comment by alefriant** [comment]
Hey @AlexThiv ! 
Using GitHub Desktop to download it works perfect, I downloaded it directly from the web->code before, thanks!
